### ISSUE TITLE
esformatter doesn't preserve newlines

### ISSUE THREAD

**Issue by fab1an** [royriojas/esformatter-jsx#75] opened 2016-06-03 10:15 UTC
For some reason esformatter won't preserve any newlines. My config:

``` javascript
    "jsx": {
        "attrsOnSameLineAsTag": false,
        "maxAttrsOnTag": 1,
        "firstAttributeOnSameLine": false,
        "alignWithFirstAttribute": false,
        "spaceInJSXExpressionContainers": "",
        "JSXExpressionsSingleLine": false,
        "htmlOptions": {
            "indent_size": 4,
            "max_preserve_newlines": 10,
            "preserve_newlines": true
        }
    },
```

**Comment by fab1an** [comment] 2016-06-08 08:41
Is there anything I can do about this? The problem is that it reformats my `Text` and `span` attributes which changes the way text is displayed, so formatting actually introduces bugs :(

**Comment by royriojas** [comment] 2016-06-09 15:34
hi @fab1an, sorry for the issues on preserving new lines

can you please send me the following:

1. A sample of code previous to formatting
2. A sample of formatted code with the issue
3. A sample of the desired output

**Comment by fab1an** [comment] 2016-06-09 16:53
And thanks for your time!

**Comment by fab1an** [comment] 2016-06-16 09:29
Any news on this?

**Comment by royriojas** [comment] 2016-06-16 09:57
hi @fab1an, I'm sorry I haven't had the time yet to take a look to it. 

It seems simple though, if someone wants to help with this PRs are welcome!

Regards

**Comment by fab1an** [comment] 2016-06-16 11:10
I don't have time for more than spotting simple bugs either :-/.

I've looked through the code, and from what I see `esformatter-jsx` send the html "between" the jsx separately through `js-beautify`. If I'm right this is the reason the options regarding newlines don't work, because there are none.

**Comment by jamtat** [comment] 2017-04-10 13:32
This is a dupe of https://github.com/royriojas/esformatter-jsx/issues/22

**Comment by jamtat** [comment] 2017-04-10 15:15
Part of the problem is https://github.com/royriojas/esformatter-jsx/blob/master/src/format-jsx.js#L155 ( `return removeEmptyLines(code.toString());` ) which calls `removeEmptyLines` on the source regardless of the preserve_newlines option. It should probably not do that.

**Comment by royriojas** [comment] 2017-04-10 18:03
Hi @jamtat you're right. The code needs some refactor. Really hate that I'm so busy these days, that I can't really make any progress on these issues. :( That said. PR's are most than welcome.

**Comment by jamtat** [comment] 2017-04-10 19:15
I made a fork earlier and pushed a commit to conditionallly remove blank
lines but it has a bug that inserts whitespace around JSXExpressions (I
think?) Which means most of the tests fail. I'll keep having little
attempts at fixing it and PR when the tests pass :)

**Closed** 2017-12-30 07:08 UTC
Labels: bug
